# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpQQ3HhfGKGYGf8oDd6WvPc1eevP1J0k
"""

import streamlit as st
import pandas as pd
import random

# --- 초기 설정 및 데이터 (실제 운영 시에는 데이터베이스 연동 권장) ---
st.set_page_config(page_title="환승 마니또 : X-Signal", layout="wide")

# 참가자 명단 (여기 30명의 이름을 넣으세요)
PARTICIPANTS = [f"참가자{i}" for i in range(1, 31)]
NICKNAMES = ["해은", "현규", "나연", "희두", "지연", "태이", "규민", "원빈", "지수", "민기",
             "나언", "현준", "서경", "주원", "유정", "창진", "다혜", "동진", "종은", "광태",
             "휘현", "혜원", "상정", "민형", "지유", "정훈", "영희", "철수", "벌꿀", "오소리"]

# 세션 상태 초기화 (데이터 휘발 방지용 - 실제 배포 시에는 DB나 파일 저장 필요)
if 'db' not in st.session_state:
    # 마니또 매칭
    targets = PARTICIPANTS[:]
    while True:
        random.shuffle(targets)
        if all(PARTICIPANTS[i] != targets[i] for i in range(len(PARTICIPANTS))):
            break

    # 참가자 정보 DB 구축
    db = {}
    for i, name in enumerate(PARTICIPANTS):
        db[name] = {
            "nickname": NICKNAMES[i],
            "target": targets[i],
            "status": "아직 선택되지 않았습니다.",
            "messages": [] # 1:1 메시지함
        }
    st.session_state.db = db
    st.session_state.global_chat = [] # 단체톡

# --- 로그인 화면 ---
if 'user' not in st.session_state:
    st.title("💘 환승 마니또 : X-Signal")
    login_name = st.selectbox("당신의 이름을 선택하세요", ["선택하세요"] + PARTICIPANTS)
    if st.button("입장하기"):
        if login_name != "선택하세요":
            st.session_state.user = login_name
            st.rerun()
else:
    user = st.session_state.user
    my_data = st.session_state.db[user]

    # 사이드바: 내 정보
    st.sidebar.title(f"👤 {my_data['nickname']}")
    st.sidebar.info(f"당신의 마니또(챙길 사람): **{my_data['target']}**")
    st.sidebar.write(f"나의 상태: {my_data['status']}")

    if st.sidebar.button("로그아웃"):
        del st.session_state.user
        st.rerun()

    # 메인 화면 탭
    tab1, tab2, tab3 = st.tabs(["💬 단체 익명톡", "💌 X-메시지 (1:1)", "🎯 오늘의 선택"])

    # 탭 1: 단체 익명톡
    with tab1:
        st.subheader("단체 익명 게시판")
        chat_input = st.text_input("메시지를 입력하세요", key="global")
        if st.button("전송", key="send_global"):
            st.session_state.global_chat.append(f"[{my_data['nickname']}] {chat_input}")
            st.rerun()

        for msg in reversed(st.session_state.global_chat):
            st.write(msg)

    # 탭 2: 1:1 메시지함 (마니또에게 보내기)
    with tab2:
        st.subheader(f"당신의 마니또({my_data['target']})에게 보내는 쪽지")
        secret_msg = st.text_area("익명으로 전달됩니다.")
        if st.button("쪽지 보내기"):
            target_user = my_data['target']
            st.session_state.db[target_user]['messages'].append(f"X로부터: {secret_msg}")
            st.success("전송 완료!")

        st.divider()
        st.subheader("나에게 온 쪽지")
        for m in reversed(my_data['messages']):
            st.write(f"📩 {m}")

    # 탭 3: 정답 맞히기
    with tab3:
        st.subheader("나의 마니또는 누구일까?")
        guess = st.selectbox("의심되는 사람을 선택하세요", ["선택하세요"] + PARTICIPANTS)
        if st.button("확인"):
            actual_manitto = ""
            # 나를 마니또로 가진 사람 찾기
            for k, v in st.session_state.db.items():
                if v['target'] == user:
                    actual_manitto = k

            if guess == actual_manitto:
                st.balloons()
                st.success("정답입니다! 당신의 마니또가 맞습니다. 🎯")
                st.session_state.db[actual_manitto]['status'] = "당신의 마니또가 당신을 선택했습니다! ❤️"
            else:
                st.error("당신의 마니또가 아닙니다. 🤫")
                if actual_manitto:
                    st.session_state.db[actual_manitto]['status'] = "당신의 마니또가 당신을 선택하지 않았습니다. 💔"

# --- 관리자 전용 비밀 코드 ---
ADMIN_PASSWORD = "director123"  # 운영자만 아는 비밀번호

if 'user' in st.session_state and st.session_state.user == "운영자":
    st.title("🕶️ 환승 마니또 관제 센터")

    # 1. 전체 매칭 현황 표로 보기
    st.subheader("📊 전체 매칭 현황")
    match_data = []
    for sender, info in st.session_state.db.items():
        match_data.append({
            "보내는 사람(본명)": sender,
            "닉네임": info['nickname'],
            "받는 사람(마니또)": info['target'],
            "현재 상태": info['status']
        })
    st.table(pd.DataFrame(match_data))

    # 2. 실시간 메시지 감시 (필요시)
    st.subheader("🕵️ 실시간 1:1 메시지 모니터링")
    for receiver, info in st.session_state.db.items():
        if info['messages']:
            st.write(f"**{receiver}**에게 온 메시지: {info['messages'][-1]}")

    # 3. 전체 공지사항 날리기
    st.subheader("📢 전체 공지")
    notice = st.text_input("전체 톡방에 띄울 공지")
    if st.button("공지 전송"):
        st.session_state.global_chat.append(f"🚨 [공지] {notice}")
        st.success("공지가 전송되었습니다.")

# 로그인 화면에서 운영자 접속 추가
# login_name 선택지에 "운영자"를 넣거나, 비밀번호 입력창을 따로 만듭니다.